In [8]:
import numpy as np
x = ['1', '1', '1', '0', '0', '0', '1', '0', '1', '1', 'C0', 'C1']
np.unique([n for n in x if n.isnumeric()]).shape[0]

2

In [7]:
[n for n in x if n.isnumeric()]

[]

In [4]:
import numpy as np

data = np.load('../client_descr_feature_skew_n_clients_10.npy', allow_pickle=True)


array([[ 4.00320470e-01,  3.68434727e-01,  9.76199448e-01,
         1.04262710e+00,  9.75255013e-01,  1.93638790e+00,
         1.22327328e+00,  9.28671062e-01,  1.22466171e+00,
         1.40514803e+00,  9.66458333e-01,  9.70833333e-01,
         9.26250000e-01,  9.15625000e-01,  9.36041667e-01,
         9.25208333e-01,  9.10833333e-01,  9.36458333e-01,
         9.20208333e-01,  9.00833333e-01, -2.35231584e+00,
        -9.33953422e+00,  6.33381583e+00,  1.93170492e-03,
        -1.74186414e+00, -4.22334826e+00,  6.96038346e+00,
        -5.02696744e+00, -1.41624186e+00,  1.38085817e-01,
        -2.35231584e+00, -9.33953422e+00,  6.33381583e+00,
         1.93170492e-03, -1.74186414e+00, -4.22334826e+00,
         6.96038346e+00, -5.02696744e+00, -1.41624186e+00,
         1.38085817e-01],
       [ 4.22719121e-01,  3.06638062e-01,  1.11993372e+00,
         1.03658736e+00,  1.05473959e+00,  1.88323343e+00,
         1.29644227e+00,  8.96449745e-01,  1.20084071e+00,
         1.53785646e+00,  9.62

In [6]:
data[0]

array([ 4.00320470e-01,  3.68434727e-01,  9.76199448e-01,  1.04262710e+00,
        9.75255013e-01,  1.93638790e+00,  1.22327328e+00,  9.28671062e-01,
        1.22466171e+00,  1.40514803e+00,  9.66458333e-01,  9.70833333e-01,
        9.26250000e-01,  9.15625000e-01,  9.36041667e-01,  9.25208333e-01,
        9.10833333e-01,  9.36458333e-01,  9.20208333e-01,  9.00833333e-01,
       -2.35231584e+00, -9.33953422e+00,  6.33381583e+00,  1.93170492e-03,
       -1.74186414e+00, -4.22334826e+00,  6.96038346e+00, -5.02696744e+00,
       -1.41624186e+00,  1.38085817e-01, -2.35231584e+00, -9.33953422e+00,
        6.33381583e+00,  1.93170492e-03, -1.74186414e+00, -4.22334826e+00,
        6.96038346e+00, -5.02696744e+00, -1.41624186e+00,  1.38085817e-01])

In [14]:
range(len(np.array(data))//10)

range(0, 1)

In [7]:
import copy

# client_descr_scaled
class client_descr_scaling:
    def __init__(self, 
                 scaling_method: int = 1, 
                 scaler = None, # MinMaxScaler() or StandardScaler()
                 *args,
                 **kwargs):
        self.scaling_method = scaling_method
        self.scaler = scaler
        self.scalers = None
        self.fitted = False # TODO didn't get it

    def scale(self, client_descr: np.ndarray = None) -> np.ndarray:
        # Normalize by group of descriptors
        if self.scaling_method == 1:
            if self.scalers is None:
                self.scalers = [copy.deepcopy(self.scaler) for _ in range(len(client_descr)//10)]
                
            if self.fitted:
                scaled_client_descr = np.zeros(client_descr.shape)
                for i, scaler in enumerate(self.scalers):
                    single_client_descr = client_descr[:, i*10:(i+1)*10]
                    scaled_client_descr[:, i*10:(i+1)*10] = scaler.transform(
                        single_client_descr.reshape(-1, 1)).reshape(single_client_descr.shape)
                
            else:
                self.fitted = True
                scaled_client_descr = np.zeros(client_descr.shape)
                for i, scaler in enumerate(self.scalers):
                    single_client_descr = client_descr[:, i*10:(i+1)*10]
                    if i == 0:
                        print(single_client_descr)
                    scaled_client_descr[:, i*10:(i+1)*10] = scaler.fit_transform(
                        single_client_descr.reshape(-1, 1)).reshape(single_client_descr.shape)
            
            return scaled_client_descr
        
        elif self.scaling_method == 2:
            # TODO weighted scaling
            return None
        
        else:
            print("Invalid scaling method!")
            return None

In [8]:
from sklearn.preprocessing import MinMaxScaler
descriptors_scaler = client_descr_scaling(scaling_method=1,
                                              scaler=MinMaxScaler(),
                                              )

In [12]:
descriptors_scaler.scale(np.array(data))

array([[0.06031253, 0.04080646, 0.41260583, 0.45324286, 0.41202807,
        1.        , 0.56375296, 0.38353039, 0.56460233, 0.67501463,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.07401488, 0.00300242, 0.5005351 , 0.44954806, 0.46065267,
        0.96748282, 0.608514  , 0.36381904, 0.55002986, 0.75619885,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0. 