In [2]:
import torch 

In [6]:
target = torch.tensor([1, 2, 3, 4, 5])
latent_space = torch.ones(10, 1)
for i in range(len(target)):
    # print(torch.sin(target[i]/(10000**(torch.arange(len([1]))/len(latent_space[i])))))
    print(latent_space[i] + latent_space[i] * torch.sin(torch.ones_like(latent_space[i])*target[i]/(10000**(torch.arange(len(latent_space[i]))/len(latent_space[i])))))

tensor([1.8415])
tensor([1.9093])
tensor([1.1411])
tensor([0.2432])
tensor([0.0411])


In [ ]:
latent_space

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

: 